name: stistools
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - numpydoc
  - sphinx=1.8
  - d2to1
  - pip:
    - stsci_rtd_theme
    - sphinx_automodapi
