name: stistools
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - numpy
  - numpydoc
  - sphinx>=1.5
  - ipython
  - d2to1
  - stsci.distutils
  - pip:
    - sphinx_rtd_theme
    - stsci_rtd_theme
    - sphinx_automodapi
