name: stistools
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - numpydoc
  - astropy>=4.1
  - scipy
  - sphinx=1.8
  - stsci.tools
  - ipython
  - d2to1
  - stsci.distutils
  - stsci.tools
  - pip:
    - stsci_rtd_theme
    - sphinx_automodapi
