name: Publish to PyPI

on:
  release:
    types: [released]

jobs:
  publish:
    uses: spacetelescope/action-publish_to_pypi/.github/workflows/workflow.yml@db1a5633a75b441416f9bf6790ae78fb5f3bf970  # 1.2.4
    with:
      test: false
      build_platform_wheels: false  # Set to true if your package contains a C extension
    secrets:
      user: ${{ secrets.PYPI_USERNAME_STSCI_MAINTAINER }}
      password: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }} # WARNING: Do not hardcode secret values here! If you want to use a different user or password, you can override this secret by creating one with the same name in your Github repository settings.
      test_password: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER_TEST }}
